on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: |
          ls -l

      - name: Run hello.py and save output
        run: |
          python hello.py > output.txt

      - name: Upload hello.py output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-output
          path: output.txt