name: New Workflow

on: [push, pull_request]

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: List files
        run: |
          echo "Files in the repository:"
          ls -la

      - name: Run hello.py
        run: |
          echo "Running hello.py"
          python hello.py