on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: List files
        run: |
          ls -l
      # You can test your matrix by printing the current Python version
      - name: run hello.py
        run: |
          python hello.py


